#!/bin/bash
docker-compose -f docker-compose.yml up -d
docker-compose -f docker-compose.yml exec exams python manage.py migrate
docker-compose -f docker-compose.yml exec exams python manage.py collectstatic
docker-compose -f docker-compose.yml exec exams cp -r /app/collected_static/. /static/static
docker-compose -f docker-compose.yml exec exams python manage.py loaddata db.json
echo Test the endpoints