# Generated by Django 4.2.5 on 2023-09-13 19:56

import uuid

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Labs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="public.labs",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="labs",
            trigger=pgtrigger.compiler.Trigger(
                name="catch_update_timestamp",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.updated_at = now(); RETURN NEW;",
                    hash="d290486ec7b7a332c948e37817094b534f00cbe6",
                    operation="UPDATE",
                    pgid="pgtrigger_catch_update_timestamp_37f1c",
                    table="public_labs",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tests",
            trigger=pgtrigger.compiler.Trigger(
                name="catch_update_timestamp",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.updated_at = now(); RETURN NEW;",
                    hash="3998267f7ff581467a43dc642f3afb0be9f14ab5",
                    operation="UPDATE",
                    pgid="pgtrigger_catch_update_timestamp_942c5",
                    table="public_tests",
                    when="BEFORE",
                ),
            ),
        ),
    ]
